### ISSUE TITLE
[EPIC] Defects Controller 

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/Kv-012#72]
- [x] Fix the template due to the [requirements](https://github.com/ITsvetkoFF/Kv-012/wiki)
- [x] Try to fill the template with faker data 
- [x] When you see that everything looks awful - implement better template (staying in touch with other guys from other EPICS to provide the same UX)
- [x] Think on other tasks for this epic (or general tasks)
