### ISSUE TITLE
[RUNS EPIC] Redesign our test run execution page

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/Kv-012#88]
- [ ] It should looks like our other pages
- [ ] It should contain functions to create the test run.
- [ ] And also this ui-route should accept some data from test runs page (when clicking "copy and run" action button)
